export const SET_SEARCHED_MOVIES = 'SET_SEARCHED_MOVIES';

export const SET_TAB = 'SET_TAB';

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';

export const NAVIGATION_BACK = 'NAVIGATION_BACK';

export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';

export const SET_FAVORITE_MOVIES = 'SET_FAVORITE_MOVIES';
